#! /bin/bash
#===============================
#
# lib
#
# 2022/10/31 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
DATE=`date -I`
KEGG_FILE_=/tmp/kegg-
KEGG_FILE=${KEGG_FILE_}${DATE}
get_kegg() {
	[ -f ${KEGG_FILE} ] && return

	rm -f ${KEGG_FILE_}*

	wget 'https://www.genome.jp/kegg-bin/download_htext?htext=ko00001&format=htext&filedir=' -O ${KEGG_FILE}
}

get_genomes() {
	GENOME_LIST=`cut -d "|" -f 2 $1 | awk '{print $1}' | sed -e 's/_[0-9]*$//g' | sort | uniq`
	GENOME_NUM=`echo "${GENOME_LIST}" | wc -l`

	KNUM_LIST=`grep -w -E "K([0-9]){5}" $1 | awk '{print $2}'`
	KNUM_NUM=`echo "${KNUM_LIST}" | wc -l`

	KNUM_UNIQ_LIST=`echo "${KNUM_LIST}" | sort | uniq`
	KNUM_UNIQ_NUM=` echo "${KNUM_LIST}" | sort | uniq | wc -l`
}
