#! /bin/bash
#===============================
#
# get_knum_name
#
# 2026/02/06 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname | xargs dirname`

. ${TOP}/lib_kegg

KNUM_FILE=$1
KEGG_FILE=$2
OUT=$3
SINGLE_KNAME=$4

for knum in `cat ${KNUM_FILE}`
do
	kegg_knum_name ${OUT} ${knum} ${KEGG_FILE} ${SINGLE_KNAME}
done
