#! /bin/bash
#===============================
#
# out_tr
#
# 2026/02/06 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname | xargs dirname`
. ${TOP}/mo_genome_function2/lib
. ${TOP}/lib_kegg

KNUM=$1
TITLE=$2

